# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.10.1
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups:
- product_supplierinfo_for_customer
- uom_qty_unique
repo_description: 'TODO: add repo description.'
repo_name: product-attribute
repo_slug: product-attribute
repo_website: https://github.com/OCA/product-attribute
travis_apt_packages: []
travis_apt_sources: []

