from . import country_restriction_mixin
from . import res_company
from . import product_country_restriction
from . import product_country_restriction_item
from . import product_country_restriction_rule
from . import product_product
from . import product_template
from . import res_country
from . import res_partner
