from . import dimensions_mixin
from . import dimension_rule
from . import dimension_exclusion_rule
from . import product_attribute
from . import product_template
from . import product_product
from . import sale_order_line
from . import product_pricelist_item
from . import product_pricelist
from . import sale_order
