[project]
name = "odoo-addons-oca-product-attribute"
version = "19.0.20260520.0"
dependencies = [
    "odoo-addon-product_attribute_archive==19.0.*",
    "odoo-addon-product_attribute_value_avoid_auto_fill==19.0.*",
    "odoo-addon-product_category_active==19.0.*",
    "odoo-addon-product_category_code==19.0.*",
    "odoo-addon-product_category_type==19.0.*",
    "odoo-addon-product_category_uom==19.0.*",
    "odoo-addon-product_code_unique==19.0.*",
    "odoo-addon-product_company_default==19.0.*",
    "odoo-addon-product_customerinfo==19.0.*",
    "odoo-addon-product_dimension==19.0.*",
    "odoo-addon-product_drained_weight==19.0.*",
    "odoo-addon-product_manufacturer==19.0.*",
    "odoo-addon-product_net_weight==19.0.*",
    "odoo-addon-product_pricelist_item_list_view==19.0.*",
    "odoo-addon-product_pricelist_revision==19.0.*",
    "odoo-addon-product_state==19.0.*",
    "odoo-addon-product_state_sale==19.0.*",
    "odoo-addon-product_status==19.0.*",
    "odoo-addon-product_supplierinfo_indirect_cost==19.0.*",
    "odoo-addon-purchase_product_template_tags==19.0.*",
    "odoo-addon-uom_alias==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
