[project]
name = "odoo-addons-oca-product-attribute"
version = "17.0.20251007.0"
dependencies = [
    "odoo-addon-product_assortment>=17.0dev,<17.1dev",
    "odoo-addon-product_attribute_auto_add>=17.0dev,<17.1dev",
    "odoo-addon-product_attribute_company_favorite>=17.0dev,<17.1dev",
    "odoo-addon-product_category_active>=17.0dev,<17.1dev",
    "odoo-addon-product_category_code>=17.0dev,<17.1dev",
    "odoo-addon-product_category_code_unique>=17.0dev,<17.1dev",
    "odoo-addon-product_category_product_link>=17.0dev,<17.1dev",
    "odoo-addon-product_code_mandatory>=17.0dev,<17.1dev",
    "odoo-addon-product_code_unique>=17.0dev,<17.1dev",
    "odoo-addon-product_company_default>=17.0dev,<17.1dev",
    "odoo-addon-product_cost_security>=17.0dev,<17.1dev",
    "odoo-addon-product_dimension>=17.0dev,<17.1dev",
    "odoo-addon-product_document_domain>=17.0dev,<17.1dev",
    "odoo-addon-product_form_pricelist>=17.0dev,<17.1dev",
    "odoo-addon-product_logistics_uom>=17.0dev,<17.1dev",
    "odoo-addon-product_logistics_uom_total_weight>=17.0dev,<17.1dev",
    "odoo-addon-product_lot_sequence>=17.0dev,<17.1dev",
    "odoo-addon-product_main_supplierinfo>=17.0dev,<17.1dev",
    "odoo-addon-product_manufacturer>=17.0dev,<17.1dev",
    "odoo-addon-product_multi_category>=17.0dev,<17.1dev",
    "odoo-addon-product_multi_code>=17.0dev,<17.1dev",
    "odoo-addon-product_net_weight>=17.0dev,<17.1dev",
    "odoo-addon-product_packaging_dimension>=17.0dev,<17.1dev",
    "odoo-addon-product_packaging_level>=17.0dev,<17.1dev",
    "odoo-addon-product_packaging_level_salable>=17.0dev,<17.1dev",
    "odoo-addon-product_pricelist_assortment>=17.0dev,<17.1dev",
    "odoo-addon-product_pricelist_by_contact>=17.0dev,<17.1dev",
    "odoo-addon-product_pricelist_direct_print>=17.0dev,<17.1dev",
    "odoo-addon-product_pricelist_fixed_currency_rate>=17.0dev,<17.1dev",
    "odoo-addon-product_pricelist_item_list_view>=17.0dev,<17.1dev",
    "odoo-addon-product_pricelist_revision>=17.0dev,<17.1dev",
    "odoo-addon-product_pricelist_simulation>=17.0dev,<17.1dev",
    "odoo-addon-product_pricelist_supplierinfo>=17.0dev,<17.1dev",
    "odoo-addon-product_print_category>=17.0dev,<17.1dev",
    "odoo-addon-product_product_template_link>=17.0dev,<17.1dev",
    "odoo-addon-product_readonly_security>=17.0dev,<17.1dev",
    "odoo-addon-product_restricted_type>=17.0dev,<17.1dev",
    "odoo-addon-product_route_mto>=17.0dev,<17.1dev",
    "odoo-addon-product_secondary_unit>=17.0dev,<17.1dev",
    "odoo-addon-product_sequence>=17.0dev,<17.1dev",
    "odoo-addon-product_set>=17.0dev,<17.1dev",
    "odoo-addon-product_state>=17.0dev,<17.1dev",
    "odoo-addon-product_state_sale>=17.0dev,<17.1dev",
    "odoo-addon-product_state_stock_base>=17.0dev,<17.1dev",
    "odoo-addon-product_status>=17.0dev,<17.1dev",
    "odoo-addon-product_supplierinfo_archive>=17.0dev,<17.1dev",
    "odoo-addon-product_supplierinfo_code>=17.0dev,<17.1dev",
    "odoo-addon-product_supplierinfo_for_customer>=17.0dev,<17.1dev",
    "odoo-addon-product_supplierinfo_revision>=17.0dev,<17.1dev",
    "odoo-addon-product_uom_measure_type>=17.0dev,<17.1dev",
    "odoo-addon-product_usability>=17.0dev,<17.1dev",
    "odoo-addon-purchase_product_template_tags>=17.0dev,<17.1dev",
    "odoo-addon-sale_product_matrix_secondary_unit>=17.0dev,<17.1dev",
    "odoo-addon-sale_product_template_tags>=17.0dev,<17.1dev",
    "odoo-addon-stock_product_template_tags>=17.0dev,<17.1dev",
    "odoo-addon-stock_production_lot_expired_date>=17.0dev,<17.1dev",
    "odoo-addon-uom_alias>=17.0dev,<17.1dev",
    "odoo-addon-uom_category_active>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
