{
    "name": "Product Pricelist Item Menu",
    "version": "14.0.1.0.0",
    "summary": "Product Pricelist Item Menu",
    "author": "Ooops, Cetmix, Odoo Community Association (OCA)",
    "license": "LGPL-3",
    "category": "Productivity",
    "website": "https://github.com/OCA/product-attribute",
    "depends": [
        "stock",
        "sale_management",
        "sale_product_configurator",
        "uom",
    ],
    "data": [
        "data/data.xml",
        "data/assets.xml",
        "security/ir.model.access.csv",
        "views/product_attribute.xml",
        "views/product_template.xml",
        "views/dimension_rule.xml",
        "views/product_attribute.xml",
        "views/product_tmpl_att_value.xml",
        "views/product_configurator_template.xml",
        "views/dimension_exclusion_rule.xml",
        "views/product_pricelist_item.xml",
    ],
    "demo": [
        "demo/0001_demo_product_dimension_attributtes.xml",
        "demo/0002_demo_product_categories.xml",
        "demo/0008_demo_attributes.xml",
        "demo/0010_demo_product_test_product_link_10.xml",
        "demo/0009_demo_product_category_linked_products.xml",
        "demo/0003_demo_product_test_base_height_never_with_bm.xml",
        "demo/0004_demo_product_test_base_area_always_with_bm.xml",
        # "demo/0005_demo_product_test_base_area_never_with_bm.xml",
        # "demo/0006_demo_product_test_base_height_always_no_bm.xml",
        # "demo/0007_demo_product_test_base_height_never_no_bm.xml",
        # "demo/0008_demo_product_test_base_area_always_no_bm.xml",
        # "demo/0010_demo_product_test_base_area_never_no_BM.xml",
        # "demo/0020_demo_product_test_base_height_and_width_exclusion.xml",
        # "demo/0030_demo_exclusion_blue_if_height_more_1000_AND_width_more_1000.xml",
        # "demo/0040_demo_product_test_attribute_product_link.xml",
        # "demo/0050_demo_ptav_on_attribute_value_net_color_blue.xml",
        # "demo/0060_demo_ptav_on_attribute_value_net_color_orange.xml",
        # "demo/0070_demo_ptav_on_attribute_value_net_color_green.xml",
        # "demo/0110_demo_product_test_base_fixed_price.xml",
        # "demo/0130_demo_product_test_base_height_always_with_bm.xml",
        # "demo/0170_demo_product_test_base_area_exclusion.xml",
        # "demo/0180_demo_product_test_base_height_exclusion.xml",
        # "demo/0190_demo_exclusion_rule_exclude_blue_if_area_gt_2.xml",
        # "demo/0200_demo_exclusion_rule_exclude_blue_if_height_gt_2000.xml",
        # "demo/0210_demo_product_test_linked_area_never_no_bm.xml",
        # "demo/0220_demo_product_test_linked_area_always_no_bm.xml",
        # "demo/0230_demo_product_test_linked_height_never_no_bm.xml",
        # "demo/0240_demo_product_test_linked_height_always_no_bm.xml",
        # "demo/0250_demo_product_test_linked_area_never_with_bm.xml",
        # "demo/0260_demo_product_test_linked_area_always_with_bm.xml",
        # "demo/0270_demo_product_test_linked_height_never_with_bm.xml",
        # "demo/0280_demo_product_test_linked_height_always_with_bm.xml",
        "demo/0290_demo_pricellist_dimension_in_pricelist.xml",
        # "demo/0300_demo_product_test_base_fixed_no_dimension.xml",
    ],
    "qweb": [],
    "installable": True,
    "application": False,
}
